config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    #名前は必須入力かつ20文字以内
    validates :name , length: { maximum: 20 } , presence: true
    #年齢は必須入力かつ数字のみ2桁以下
    validates :age , length:{ maximum:2 , } , numericality:{ only_integer: true, greater_than_or_equal_to: 1 } , presence: true
    #内容は必須入力かつ2文字以上30文字以下
    validates :body , length: {minimum: 2 , maximum: 30 } , presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  def index
    # Messageを全て取得する。
    @messages = Message.all
    @message = Message.new
  end

  ##ここから追記
 
 def create
   @message = Message.new(message_params)
   if @message.save
     redirect_to root_path , notice: 'save message'
   else
     # メッセージが保存できなかった時
     @messages = Message.all
     flash.now[:alert] = "failed save message。"
     render 'index'
    end
  end  
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'delete message'
  end  
 
def edit
end

def update
  if @message.update(message_params)
    #保存に成功した場合はトップページへリダイレクト
    redirect_to root_path , notice: 'edit message'
  else
    #保存に失敗した場合は編集画面へ戻す
    render 'edit'
  end
 end

 private
 
 def set_message
   @message = Message.find(params[:id])
 end

 def message_params
   params.require(:message).permit(:name,:age, :body)
  end
  ## ここまで

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
　<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<Br>
<body>
    <div class="container">
        <a href="#"><%=image_tag("message_board_top.png",size:"240x128") %></a>
    </div>
  <div class="container">
      <% if notice %>
       <div class="alert alert-info">
           <%= notice %>
      </div>
     <% end %>
     
   <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
 <div class="panel panel-primary",>
 <div style="padding:20px; margin-left:30px">
<%= form_for(@message) do |f| %>
 <% if @message.errors.present? %>
  <div class="alert alert-danger">
   <%= alert %>
   <ul>
     <% @message.errors.full_messages.each do |full_message| %>
      <li>
       <%= full_message %>
      </li>
     <% end %>
    </ul>
   </div>
  <% end %>
  
 name:<br>
 <%= f.text_field :name %>
 <br>
 age:<br>
 <%= f.text_field :age %>
 <br>
 message:<br>
 <%= f.text_area :body, :size=>"35x4"%><br><br>
 <%= f.submit class: "btn btn-sm btn-primary" %>
<% end %> 
</div>
</div>
 

app/views/messages/edit.html.erb
<h1>edit message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<br>
<div class="panel panel-primary">
 <div class="panel-heading">
   Messages
 </div>
 
 <div class="panel-body">
  <% @messages.each do |message| %>
   <span class="label label-info"><%= message.name %> / age:<%= message.age %></span>
   <%= message.body %>
   (<%= link_to "edit" , edit_message_path(message) %>
   <%= link_to "destroy" , message, method: :delete, data: {confirm: "Are you sure you want to delete ?"} %>)
    <br>
   <% end %>
   </div>
 </div> 
 
 <% #部分テンプレートを読み込んでいる %>
 <%= render 'form' %>